spring.application.name=Healthcare_Portal
#DB config
#DB_URL: jdbc:mysql://localhost:3306/healthbridge_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.url=${DB_URL}
#DB_USERNAME:root
spring.datasource.username=${DB_USERNAME}
#DB_PASSWORD:root123
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration - Use environment variables in production
#JWT_SECRET: BxaJJM5aX5biJKacd/9J6N/GtVxjt13UhT5UTjK7gI0/hiIlCyux5BieQWApXZ4q
jwt.secret=${JWT_SECRET}

jwt.expiration=${JWT_EXPIRATION:604800000}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#MAIL_USERNAME:healthbridge.noreply@gmail.com
spring.mail.username=${MAIL_USERNAME}
#MAIL_PASSWORD:uxhzdcouqwgdasgh
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# App Configuration
app.name=Healthcare Portal

#default server port 8080
#server.port=9090

